### ISSUE TITLE
Improve parsing of course archive XML

### ISSUE THREAD

**Issue by michaellzc** [ibm-skills-network/olx-cli#1]
The current implementation has the following disadvantage 

- it assumes each component live in its own directory, [learn more](https://edx.readthedocs.io/projects/edx-open-learning-xml/en/latest/directory-structure.html#id12)
- `R/W` operations against course XML is not consistent, sometimes it is done on disk directly and it is done in-memory. This could potentially lead to inconsistent between the content on disk and in-memory

### How to improve?

Implement some sort of data structure such that we can hold the entire course structure (XML and policies, excluding special assets, such as HTML and static assets).

### TODO

- [ ] Design the data structure to hold, XML, policies in memory.
- [ ] Implement a parser/deserializer to take a course archive as input (potentially empty input where it just initialized an empty course structure)
- [ ] Implement a serializer to transform the course structure into course archive
